### PR TITLE
Enemy asset changes

### LINKED ISSUE #191: Adjust enemy prefabs so that they have a white material
Change one of the base materials to white and remove the other prefab. This way we can have enemies that are multicolored without the red base ones all turning black

### PR DESCRIPTION
**Pull request by zalfenior**
Removed extra materials
Ensured compatibility with color-changing code
Set up models to have a light and dark version of an enemy.

Minor changes for MS3 but we can merge these in now because they do not affect anything beyond assets.

closes #191

### CODE REVIEW

**Comment by pagewin** [comment]
I want pictures, Parker!

**Comment by zalfenior** [comment]
Crawler

**Comment by zalfenior** [comment]
Baddies 01
Baddies 02
Baddies 03
Baddies 05
Baddies 04

**Comment by zalfenior** [comment]
This one will be easier by far. For me this was like an hours work and remembering where all the materials went. In all seriousness its a milestone three thing anyway

**Pull request merged**
